export const alphabetData = [
  {
    letter: "a",
    pronunciation: "ah",
    example: "aso",
    translation: "cloth",
    audio: "/assets/audio/yorubaAlphabet/a.mp3",
  },
  {
    letter: "b",
    pronunciation: "bi",
    example: "bàtà",
    translation: "ball",
    audio: "/assets/audio/yorubaAlphabet/b.mp3",
  },
  {
    letter: "d",
    pronunciation: "di",
    example: "daduro",
    translation: "stop/detain",
    audio: "/assets/audio/yorubaAlphabet/d.mp3",
  },
  {
    letter: "e",
    pronunciation: "hay",
    example: "etí",
    translation: "ear",
    audio: "/assets/audio/yorubaAlphabet/e.mp3",
  },
  {
    letter: "ẹ",
    pronunciation: "hen",
    example: "ẹja",
    translation: "fish",
    audio: "/assets/audio/yorubaAlphabet/ẹ.mp3",
  },
  {
    letter: "f",
    pronunciation: "fi",
    example: "fàmóra",
    translation: "adhere",
    audio: "/assets/audio/yorubaAlphabet/f.mp3",
  },
  {
    letter: "g",
    pronunciation: "gi",
    example: "ga",
    translation: "tall",
    audio: "/assets/audio/yorubaAlphabet/g.mp3",
  },
  {
    letter: "gb",
    pronunciation: "gbi",
    example: "gbàdurà",
    translation: "pray",
    audio: "/assets/audio/yorubaAlphabet/gb.mp3",
  },
  {
    letter: "h",
    pronunciation: "in",
    example: "hó",
    translation: "boil",
    audio: "/assets/audio/yorubaAlphabet/h.mp3",
  },
  {
    letter: "i",
    pronunciation: "hei",
    example: "ibí",
    translation: "birth",
    audio: "/assets/audio/yorubaAlphabet/i.mp3",
  },
  {
    letter: "j",
    pronunciation: "ji",
    example: "jẹun",
    translation: "eat",
    audio: "/assets/audio/yorubaAlphabet/j.mp3",
  },
  {
    letter: "k",
    pronunciation: "ki",
    example: "kà",
    translation: "read",
    audio: "/assets/audio/yorubaAlphabet/k.mp3",
  },
  {
    letter: "l",
    pronunciation: "li",
    example: "lò",
    translation: "use",
    audio: "/assets/audio/yorubaAlphabet/l.mp3",
  },
  {
    letter: "m",
    pronunciation: "mi",
    example: "mo",
    translation: "i",
    audio: "/assets/audio/yorubaAlphabet/m.mp3",
  },
  {
    letter: "n",
    pronunciation: "ni",
    example: "nla",
    translation: "great/big",
    audio: "/assets/audio/yorubaAlphabet/n.mp3",
  },
  {
    letter: "o",
    pronunciation: "oh",
    example: "ohùn",
    translation: "sound",
    audio: "/assets/audio/yorubaAlphabet/o.mp3",
  },
  {
    letter: "ọ",
    pronunciation: "or",
    example: "ọkọ",
    translation: "vehicle",
    audio: "/assets/audio/yorubaAlphabet/ọ.mp3",
  },
  {
    letter: "p",
    pronunciation: "pi",
    example: "pẹpẹrẹ",
    translation: "quick",
    audio: "/assets/audio/yorubaAlphabet/p.mp3",
  },
  {
    letter: "r",
    pronunciation: "ri",
    example: "ràra",
    translation: "not at all",
    audio: "/assets/audio/yorubaAlphabet/r.mp3",
  },
  {
    letter: "s",
    pronunciation: "si",
    example: "sùrù",
    translation: "patience",
    audio: "/assets/audio/yorubaAlphabet/s.mp3",
  },
  {
    letter: "ṣ",
    pronunciation: "shi",
    example: "ṣo",
    translation: "throw",
    audio: "/assets/audio/yorubaAlphabet/ṣ.mp3",
  },
  {
    letter: "t",
    pronunciation: "ti",
    example: "tọ",
    translation: "grind",
    audio: "/assets/audio/yorubaAlphabet/t.mp3",
  },
  {
    letter: "u",
    pronunciation: "oo",
    example: "un",
    translation: "that is",
    audio: "/assets/audio/yorubaAlphabet/u.mp3",
  },
  {
    letter: "w",
    pronunciation: "wi",
    example: "wọ",
    translation: "look",
    audio: "/assets/audio/yorubaAlphabet/w.mp3",
  },
  {
    letter: "y",
    pronunciation: "yi",
    example: "ya",
    translation: "divide",
    audio: "/assets/audio/yorubaAlphabet/y.mp3",
  },
];
