let yorubaVerbs = {
  Eat: ["jẹ", false],
  Drink: ["mu", false],
  Call: ["pè", false],
  Sleep: ["sùn", false],
  Wake: ["ji", false],
  Play: ["ṣeere", false],
  Talk: ["sọrọ", false],
  Bath: ["wẹ", false],
  Read: ["kawe", false],
  Love: ["fẹran", false],
  Pray: ["gbadura", false],
  Stand: ["dide", false],
  Walk: ["rin", false],
  Sit: ["jokoo", false],
  Clap: ["patẹwọ", false],
  Jump: ["fo", false],
  Sing: ["kọrin", false],
  Laugh: ["rẹrin", false],
  Give: ["fun", false],
  Take: ["gbà", false],
  "Take care": ["tọju", false],
  Remember: ["ranti", false],
  Forget: ["gbagbe", false],
  Forgive: ["dariji", false],
  Close: ["tì", false],
  Open: ["ṣí", false],
  Go: ["lọ", false],
  Return: ["padà", false],
  Tear: ["ya", false],
  Teach: ["kọ", false],
  Follow: ["tẹle", false],
  Fold: ["ka", false],
  Think: ["ronu", false],
  Thank: ["dupẹ", false],
  Terrify: ["dẹ́rùbà", false],
  Relax: ["farabalẹ", false],
  Wait: ["daduro", false],
  Smell: ["gborun", false],
  Rest: ["simi", false],
  Sneeze: ["sín", false],
  Run: ["sare", false],
  Start: ["bẹrẹ", false],
  Finish: ["pari", false],
};

export default yorubaVerbs;
