import "./globals.css";
import { Nunito } from "next/font/google";
const nunitoSans = Nunito({ subsets: ["latin"] });
import { LayoutProvider } from "./LayoutProvider";

export const metadata = {
  title: "Yoruba Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={nunitoSans.className}>
          <LayoutProvider>
            <main>{children}</main>
          </LayoutProvider>
        </body>
      </html>
    </>
  );
}
