import "./globals.css";
import { Nunito } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
const nunitoSans = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Yoruba Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={nunitoSans.className}>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </>
  );
}
