import "./globals.css";
import { Inter, Montserrat, Noto_Sans } from "next/font/google";
import { LayoutProvider } from "./LayoutProvider";
// import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"], display: "swap" });
const noto = Noto_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Yoruba Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* <Head> */}
      {/* <meta
        name="viewport"
        content="width=device-width, initial-scale=1, viewport-fit=cover"
      /> */}
      {/* <meta name="apple-mobile-web-app-capable" content="yes" /> */}
      {/* <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        /> */}
      {/* </Head> */}
      <html lang="en">
        <head>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, viewport-fit=cover"
          />
        </head>
        <body className={noto.className}>
          <LayoutProvider>{children}</LayoutProvider>
        </body>
      </html>
    </>
  );
}
