// src/app/layout.tsx
import "./globals.css";
import { ReactNode } from "react";
import ClientWrapper from "./ClientWrapper";

export const metadata = {
  title: "Yoruba Website",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
  pageProps?: any;
}

export default function RootLayout({ children, pageProps = {} }: LayoutProps) {
  const { session, ...otherProps } = pageProps;

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      </head>
      <body>
        <ClientWrapper session={session}>{children}</ClientWrapper>
      </body>
    </html>
  );
}
