// app/layout.tsx

import "./globals.css";
// import { Inter, Montserrat, Noto_Sans } from "next/font/google";

import { Ubuntu } from "next/font/google";

import SessionProviderWrapper from "./SessionProviderWrapper";
import dynamic from "next/dynamic";
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";

// const inter = Inter({ subsets: ["latin"] });
// const montserrat = Montserrat({ subsets: ["latin"], display: "swap" });
// const noto = Noto_Sans({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   subsets: ["latin"],
//   display: "swap",
// });

const ubuntu = Ubuntu({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Yoruba Website",
  description: "Generated by create next app",
};

const Navbar = dynamic(
  () =>
    import("@/components/Navbartw").then((mod) => mod.default) as Promise<
      React.FC<{}>
    >,
  { ssr: false },
);

const Footer = dynamic(
  () =>
    import("@/components/Footer").then((mod) => mod.default) as Promise<
      React.FC<{}>
    >,
  { ssr: false },
);

interface LayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <>
      <html lang="en">
        <head>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, viewport-fit=cover"
          />
        </head>
        <body className={ubuntu.className}>
          <SessionProviderWrapper>
            <Navbar />

            {/* {authModal} */}
            <div className="container mx-auto h-full max-w-7xl px-4 pt-12 md:px-8">
              {children}
            </div>
            <Toaster />
            <Footer />
          </SessionProviderWrapper>
        </body>
      </html>
    </>
  );
}
