let yorubaNumbers = {
  Zero: "odo",
  One: "okan",
  Two: "èjì",
  Three: "ẹ̀ta",
  Four: "ẹ̀rin",
  Five: "àrún",
  Six: "ẹ̀fà",
  Seven: "èje",
  Eight: "ẹ̀jọ",
  Nine: "ẹ̀sán",
  Ten: "ẹ̀wá",
  Eleven: "ọ̀kanlá",
  Twelve: "èjìlá",
  Thirteen: "ẹ̀talá",
  Fourteen: "ẹ̀rinlá",
  Fifteen: "ẹ́ẹdógún",
  Sixteen: "ẹẹ́rìndílógún",
  Seventeen: "eétàdílógún",
  Eighteen: "eéjìdílógún",
  Nineteen: "oókàndílógún",
  Twenty: "ogún",
  "Twenty-One": "mọkanlelogun",
  "Twenty-Two": "meji-le-logun",
  "Twenty-Three": "mẹta-le-logun",
  "Twenty-Four": "mẹrin-le-logun",
  "Twenty-Five": "arundinlogbon",
  "Twenty-Six": "meedogbon",
  "Twenty-Seven": "meta din logbon",
  "Twenty-Eight": "mejidinlogbon",
  "Twenty-Nine": "mẹẹdọgbọn",
  Thirty: "ọgbọn",
  "Thirty-One": "okanlelogbon",
  "Thirty-Two": "eji le logbon",
  "Thirty-Three": "Mẹtalelọgbọn",
  "Thirty-Four": "Mẹrinlelọgbọn",
  "Thirty-Five": "marun-din-logoji",
  "Thirty-Six": "Mẹrindilogoji",
  "Thirty-Seven": "ọgbọn-meje",
  "Thirty-Eight": "mejidinlogoji",
  "Thirty-Nine": "ọgbọn-mẹsan",
  Forty: "ogoji",
  "Forty-One": "mọkanlelogoji",
  "Forty-Two": "mejilelogoji",
  "Forty-Three": "mẹẹrinlelogoji",
  "Forty-Four": "mẹrinlelogoji",
  "Forty-Five": "marundinlogoji",
  "Forty-Six": "mejidinlogoji",
  "Forty-Seven": "mẹẹdọrin",
  "Forty-Eight": "mejidinlogoji",
  "Forty-Nine": "mẹẹdọsan",
  Fifty: "aadọta",
  Sixty: "ọgọ́ta",
  Seventy: "àádọ́rin",
  Eighty: "ọgọ́rin",
  Ninety: "àádọ́rùn",
  "One Hundred": "ọgọ́rùn",
  "One Thousand": "ẹgbẹ̀rún",
  "Ten Thousand": "ẹgbàárùn",
  "Hundred Thousand": "ọkẹ́ marun",
  "One Million": "àádọ́ta ọkẹ́",
};

export default yorubaNumbers;
